# ----------------------------------------
# Created on: Fri May 13 00:12:02 2022
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vlog   "F:/pds_project/ConvKing/source/top.v" -work work
vlog   "F:/pds_project/ConvKing/source/Bridge/axi/aq_axi_master.v" -work work
vlog   "F:/pds_project/ConvKing/source/Camera/cmos_8_16bit.v" -work work
vlog   "F:/pds_project/ConvKing/source/Camera/cmos_write_req_gen.v" -work work
vlog   "F:/pds_project/ConvKing/source/Camera/frame_fifo_read.v" -work work
vlog   "F:/pds_project/ConvKing/source/Camera/frame_fifo_write.v" -work work
vlog   "F:/pds_project/ConvKing/source/Camera/frame_read_write.v" -work work
vlog   "F:/pds_project/ConvKing/source/Camera/lut_ov5640_rgb565_1024_768.v" -work work
vlog   "F:/pds_project/ConvKing/source/Camera/i2c_master/i2c_config.v" -work work
vlog   "F:/pds_project/ConvKing/source/Camera/i2c_master/i2c_master_bit_ctrl.v" -work work
vlog   "F:/pds_project/ConvKing/source/Camera/i2c_master/i2c_master_byte_ctrl.v" -work work
vlog   "F:/pds_project/ConvKing/source/Camera/i2c_master/i2c_master_defines.v" -work work
vlog   "F:/pds_project/ConvKing/source/Camera/i2c_master/i2c_master_top.v" -work work
vlog   "F:/pds_project/ConvKing/source/Uart/uart_rx.v" -work work
vlog   "F:/pds_project/ConvKing/source/Uart/uart_top.v" -work work
vlog   "F:/pds_project/ConvKing/source/Uart/uart_tx.v" -work work
vlog   "F:/pds_project/ConvKing/source/mult_add.v" -work work
vlog   "F:/pds_project/ConvKing/source/Peripheral/Hdmi/dvi_tx/dvi_encoder.v" -work work
vlog   "F:/pds_project/ConvKing/source/Peripheral/Hdmi/dvi_tx/encode.v" -work work
vlog   "F:/pds_project/ConvKing/source/Peripheral/Hdmi/dvi_tx/serdes_4b_10to1.v" -work work
vlog   "F:/pds_project/ConvKing/source/Peripheral/Hdmi/color_bar.v" -work work
vlog   "F:/pds_project/ConvKing/source/Peripheral/Hdmi/video_define.v" -work work
vlog   "F:/pds_project/ConvKing/source/Peripheral/Hdmi/video_timing_data.v" -work work
vlog   "F:/pds_project/ConvKing/source/Peripheral/key.v" -work work
vlog   "F:/pds_project/ConvKing/source/Peripheral/key_top.v" -work work
vlog   "F:/pds_project/ConvKing/source/Accelerator/ReLU/relu.v" -work work
vlog   "F:/pds_project/ConvKing/source/Accelerator/ReLU/relu_top.v" -work work
vlog   "F:/pds_project/ConvKing/source/Accelerator/Linear/linear.v" -work work
vlog   "F:/pds_project/ConvKing/source/Accelerator/Linear/linear_top.v" -work work
vlog   "F:/pds_project/ConvKing/source/Accelerator/mobilenet_invres.v" -work work
vlog   "F:/pds_project/ConvKing/source/Accelerator/mobilenet_top.v" -work work
vlog   "F:/pds_project/ConvKing/source/Accelerator/yolo_aft.v" -work work
vlog   "F:/pds_project/ConvKing/source/Accelerator/yolo_CBL.v" -work work
vlog   "F:/pds_project/ConvKing/source/Accelerator/yolo_mobilenet.v" -work work
vlog   "F:/pds_project/ConvKing/source/Accelerator/yolo_pre.v" -work work
vlog   "F:/pds_project/ConvKing/source/Accelerator/yolo_top.v" -work work
vlog   "F:/pds_project/ConvKing/source/Peripheral/Sdcard/sd_card_cmd.v" -work work
vlog   "F:/pds_project/ConvKing/source/Peripheral/Sdcard/sd_card_sec_read_write.v" -work work
vlog   "F:/pds_project/ConvKing/source/Peripheral/Sdcard/sd_card_top.v" -work work
vlog   "F:/pds_project/ConvKing/source/Peripheral/Sdcard/spi_master.v" -work work
vlog   "F:/pds_project/ConvKing/source/Peripheral/ax_debounce.v" -work work
vlog   "F:/pds_project/ConvKing/source/Peripheral/pt_read.v" -work work
vlog   "F:/pds_project/ConvKing/source/Peripheral/sd_card_weight.v" -work work
vlog   "F:/pds_project/ConvKing/source/Uart/uart_decode.v" -work work
vlog   "F:/pds_project/ConvKing/source/Accelerator/KNN/color_det_top.v" -work work
vlog   "F:/pds_project/ConvKing/source/Accelerator/KNN/rgb2hsv.v" -work work
vlog   "F:/pds_project/ConvKing/source/Accelerator/KNN/hsv2rgb.v" -work work
vlog   "F:/pds_project/ConvKing/source/Accelerator/KNN/histogram.v" -work work
vlog   "F:/pds_project/ConvKing/ipcore/video_pll/video_pll.v" -work work
vlog   "F:/pds_project/ConvKing/ipcore/afifo_16i_64o_512/rtl/ipml_fifo_ctrl_v1_3.v" -work work
vlog   "F:/pds_project/ConvKing/ipcore/afifo_16i_64o_512/rtl/ipml_sdpram_v1_5_afifo_16i_64o_512.v" -work work
vlog   "F:/pds_project/ConvKing/ipcore/afifo_16i_64o_512/rtl/ipml_fifo_v1_5_afifo_16i_64o_512.v" -work work
vlog   "F:/pds_project/ConvKing/ipcore/afifo_16i_64o_512/afifo_16i_64o_512.v" -work work
vlog   "F:/pds_project/ConvKing/ipcore/afifo_64i_16o_128/rtl/ipml_fifo_ctrl_v1_3.v" -work work
vlog   "F:/pds_project/ConvKing/ipcore/afifo_64i_16o_128/rtl/ipml_sdpram_v1_5_afifo_64i_16o_128.v" -work work
vlog   "F:/pds_project/ConvKing/ipcore/afifo_64i_16o_128/rtl/ipml_fifo_v1_5_afifo_64i_16o_128.v" -work work
vlog   "F:/pds_project/ConvKing/ipcore/afifo_64i_16o_128/afifo_64i_16o_128.v" -work work
vlog   "F:/pds_project/ConvKing/ipcore/mult_add_gen/rtl/ipml_multadd_v1_1_mult_add_gen.v" -work work
vlog   "F:/pds_project/ConvKing/ipcore/mult_add_gen/mult_add_gen.v" -work work
vlog   "F:/pds_project/ConvKing/ipcore/ddr3_core/rtl/pll/pll_50_400_v1_1.v" -work work
vlog   "F:/pds_project/ConvKing/ipcore/ddr3_core/rtl/ipsl_hmic_h_ddrc_apb_reset_v1_1.v" -work work
vlog   "F:/pds_project/ConvKing/ipcore/ddr3_core/rtl/ipsl_hmic_h_ddrc_reset_ctrl_v1_1.v" -work work
vlog   "F:/pds_project/ConvKing/ipcore/ddr3_core/rtl/ipsl_hmic_h_ddrphy_dll_update_ctrl_v1_1.v" -work work
vlog   "F:/pds_project/ConvKing/ipcore/ddr3_core/rtl/ipsl_hmic_h_ddrphy_reset_ctrl_v1_1.v" -work work
vlog   "F:/pds_project/ConvKing/ipcore/ddr3_core/rtl/ipsl_hmic_h_ddrphy_training_ctrl_v1_1.v" -work work
vlog   "F:/pds_project/ConvKing/ipcore/ddr3_core/rtl/ipsl_hmic_h_ddrphy_update_ctrl_v1_1.v" -work work
vlog   "F:/pds_project/ConvKing/ipcore/ddr3_core/rtl/ipsl_hmic_h_ddrc_top_v1_1.v" -work work
vlog   "F:/pds_project/ConvKing/ipcore/ddr3_core/rtl/ipsl_hmic_h_phy_top_v1_1.v" -work work
vlog   "F:/pds_project/ConvKing/ipcore/ddr3_core/rtl/ipsl_hmic_h_phy_io_v1_1.v" -work work
vlog   "F:/pds_project/ConvKing/ipcore/ddr3_core/ddr3_core.v" -work work
vlog   "F:/pds_project/ConvKing/ipcore/afifo_32i_8o_64depth/rtl/ipml_fifo_ctrl_v1_3.v" -work work
vlog   "F:/pds_project/ConvKing/ipcore/afifo_32i_8o_64depth/rtl/ipml_sdpram_v1_5_afifo_32i_8o_64depth.v" -work work
vlog   "F:/pds_project/ConvKing/ipcore/afifo_32i_8o_64depth/rtl/ipml_fifo_v1_5_afifo_32i_8o_64depth.v" -work work
vlog   "F:/pds_project/ConvKing/ipcore/afifo_32i_8o_64depth/afifo_32i_8o_64depth.v" -work work
vlog   "F:/pds_project/ConvKing/ipcore/afifo_8i_32o_64depth/rtl/ipml_fifo_ctrl_v1_3.v" -work work
vlog   "F:/pds_project/ConvKing/ipcore/afifo_8i_32o_64depth/rtl/ipml_sdpram_v1_5_afifo_8i_32o_64depth.v" -work work
vlog   "F:/pds_project/ConvKing/ipcore/afifo_8i_32o_64depth/rtl/ipml_fifo_v1_5_afifo_8i_32o_64depth.v" -work work
vlog   "F:/pds_project/ConvKing/ipcore/afifo_8i_32o_64depth/afifo_8i_32o_64depth.v" -work work
vlog   "F:/pds_project/ConvKing/ipcore/histogram_ram_h/rtl/ipml_dpram_v1_5_histogram_ram_h.v" -work work
vlog   "F:/pds_project/ConvKing/ipcore/histogram_ram_h/histogram_ram_h.v" -work work
vlog   "F:/pds_project/ConvKing/ipcore/histogram_ram_s/rtl/ipml_dpram_v1_5_histogram_ram_s.v" -work work
vlog   "F:/pds_project/ConvKing/ipcore/histogram_ram_s/histogram_ram_s.v" -work work
vlog   "F:/pds_project/ConvKing/ipcore/histogram_ram_v/rtl/ipml_dpram_v1_5_histogram_ram_v.v" -work work
vlog   "F:/pds_project/ConvKing/ipcore/histogram_ram_v/histogram_ram_v.v" -work work
vlog   "F:/pds_project/ConvKing/source/Accelerator/KNN/tb/hist_top_tb.v" -work work

# ----------------------------------------
