# ----------------------------------------
# Created on: Fri May 13 00:12:02 2022
# Auto generated by Pango
# ----------------------------------------

vsim  -voptargs="+acc" -L work hist_top_tb
add wave *
view wave
view structure
view signals

run 1000ns

# ----------------------------------------
